theme: jekyll-theme-cayman

github:
  is_project_page: false
  
markdown: kramdown
kramdown:
  math_engine: katex

title: MuseMorphose
description: Full-Song and Fine-Grained Music Style Transfer with One Transformer VAE
